#!/bin/bash
#set -e	

export MSYS_NO_PATHCONV=1


cd "$(dirname "${0}")" || exit

chmod +x ./web/code/vendor/phpunit/phpunit/phpunit
echo -e $(pwd)
# This is a workaround for a difference of opinion between Docker and WSL
realPwd() {
 temp=$( pwd | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/' )
 echo "$temp"
}
echo "pwd $(pwd)"

testRealPwd=$(realPwd)
echo "realPwd $testRealPwd"

ENV="$(printenv)"
echo $ENV


if [ -z "$ENV" ]
then
    echo "Missing environment file"

    if [ -f ".env.dist" ]
    then
        echo "Found .env.dist file. Type \"yes\" to create .env file."
        read -r env_create_confirm
        
        if [ "$env_create_confirm" == "yes" ]; then
            cp .env.dist .env
        else
            # Failed to confirm automatic .env creation
            exit 1
        fi
    else
        # Missing .env and .env.dist
        exit 1
    fi
fi

# Export the environment variables for docker-compose
set -a
# shellcheck disable=SC1091
source "./.env"
set +a

PROJECT=${APP}${ENV}

echo 'project is ' "${PROJECT}"

SUBCOMMAND=
declare -a SUBCOMMAND_ARGS


case "$(uname -s)" in
    MINGW32*|MINGW64*)
        WINPTY=1
        ;;
    *)
        WINPTY=0
        ;;
esac

initDockerCompose() {
    docker-compose -f docker-compose.yml -p build "$PROJECT" "$@"
}


initDockerComposeRun() {
     docker-compose -f docker-compose.yml -p "$PROJECT" run --rm "$@"
}

initDockerComposeDown() {
    docker-compose -f docker-compose.yml -p "$PROJECT" kill
    docker-compose -f docker-compose.yml -p "$PROJECT" rm
    docker-compose -f docker-compose.yml -p "$PROJECT" down -v --remove-orphans "$@"
}

initDockerComposeBuild() {
    docker-compose build
}    

testDockerCompose() {
    docker-compose -f docker-compose-test.yml -p "${PROJECT}test" "$@"
}

testDockerComposeRun() {
    docker-compose -f docker-compose-test.yml -p "${PROJECT}test" run --rm "$@"
}

clearContainerCache() {
    initDockerComposeRun web bash "$(pwd)/scripts/clear-container-cache.sh"
}

echo " ** {$@}  ** " 
for ARG in "$@"; do
    if [ x"$SUBCOMMAND" != x ]; then
        SUBCOMMAND_ARGS["${#SUBCOMMAND_ARGS[@]}"]="$ARG"
        echo ${SUBCOMMAND_ARGS}
    elif [ x"$in_env" = xtrue ]; then
        eval "export $ARG"
        in_env=false
    elif [ x"$ARG" = x-v ] || [ x"$ARG" = x--verbose ]; then
        set -x
    elif [ x"$ARG" = x-e ] || [ x"$ARG" = x--env ]; then
        in_env=true
    elif [ x"$ARG" = x-h ] || [ x"$ARG" = x--help ]; then
        SUBCOMMAND=help
    else
        SUBCOMMAND="$ARG"
    fi
done

case "$SUBCOMMAND" in
    shell)
        SERVICE_NAME=
        IS_TEST=0
        for arg in SUBCOMMAND_ARGS[$@]; do
          if [ "#x$arg" == "#"x--test ]; then
            IS_TEST=1
          elif [ "#x$arg" == "#"x--help ]; then
            cat <<EOF
Usage:
bash haz shell [--test] [SERVICE_NAME]
bash haz shell --help

Options:
--help          Show this message
--test          Use the test version of the service
SERVICE_NAME    The docker-compose container service name

Examples:
bash haz shell --test api    Enter the test API container
EOF
            exit
          else
            SERVICE_NAME="$arg"
          fi
        done

        if [ $IS_TEST = 1 ]; then
            PROJ="${PROJECT}test"
        else
            PROJ="${PROJECT}"
        fi
        

        CONTAINER_NAME="${PROJ}_${SERVICE_NAME}_1"

        if [ $WINPTY = 1 ]; then
            ECHO 'WINPTY'
            winpty docker exec -it "$CONTAINER_NAME" //bin/bash
        else
            echo 'no WINPTY'
            docker exec -it "$CONTAINER_NAME" //bin/bash
        fi
        ;;
    composer)
        # Usage: ./haz composer update --ignore-platform-reqs
        docker run --rm --interactive --volume "$(pwd)/web/code":/app composer:1.8 "${#SUBCOMMAND_ARGS[@]}"
        ;;  
    clean)
        # Careful when running this command. It will only remove generated
        # containers/networks but will purge ALL dangling images/volumes
        echo "> Removing containers:"
        docker rm -f "$(docker ps -qa --no-trunc --filter "name=${PROJECT}")" >2 /dev/null

        echo -e "\n> Removing dangling volumes:"
        docker volume rm $(docker volume ls -q --filter "dangling=true")  >2 /dev/null
        
        echo -e "\n> Removing networks:"
        docker network rm $(docker network ls -q --filter "name=${PROJECT}") >2 /dev/null
        
        echo -e "\n> Removing dangling images:"
        docker rmi -f $(docker images -q --no-trunc --filter "dangling=true") 2> /dev/null
        echo -e "\n> Done cleaning"
        ;;
    setup)
        if [ ${#SUBCOMMAND_ARGS[@]} != 0 ]; then
            echo "Usage: bash haz setup"
            exit 1
        fi

        # Incase something changed, clear the DI container caches to force a rebuild
        clearContainerCache

        mkdir -p web-nginx/code
        
        initDockerComposeDown
        initDockerComposeBuild
        initDockerComposeRun mysql sh ./srv/scripts/init.sh 2>&1 
        ;;
    start)
        initDockerComposeRun -d "${SUBCOMMAND_ARGS[${@}]}"
        docker ps -a
        ;;
    stop)
        initDockerComposeDown "${SUBCOMMAND_ARGS[${@}]}"
        ;;
    reset)
        initDockerComposeDown "${SUBCOMMAND_ARGS[${@}]}"

        initDockerComposeRun mysql  sh "$(pwd)/srv/scripts/init.sh"
        initDockerComposeRun -d "${SUBCOMMAND_ARGS[${@}]}"
        ;;
    reset-test)
        initDockerComposeDown  "${PROJECT}test"

        testDockerComposeRun mysql sh "$(pwd)/srv/scripts/init.sh" 
        testDockerCompose up -d
        ;;
    test)
    
        reset_db=1
        no_tear_down=0
         for arg in SUBCOMMAND_ARGS[{$@}]}; do
          if ["x--${arg}" == 'x--no-reset-db' ]; then
            reset_db=0
          elif [ "x${arg}" == 'x--noTearDown' ]; then
            no_tear_down=1
          elif [ "x${arg}" == 'x--help' ]; then
            cat <<EOF
Usage:
  bash haz test [--web] [--no-reset-db]
  bash haz test --help

Options:
  -h | --help     Show this message
  --no-reset-db   Do not reset the database
  --no-tear-down  Exit after the test suite completes and do not remove the test containers

Examples:
  bash haz test    Run the test suite
EOF
            exit 1
          fi
        done
        clearContainerCache
        mkdir -p web-nginx/code
        testDockerCompose build 2>&1
        if [ x$reset_db != x0 ]; then
            echo -e "\n> Rebuilding test db"
            testDockerComposeRun mysql  sh "$(pwd)/srv/scripts/init.sh" 2>&1 
        fi

        testDockerCompose start -d 2>&1

        echo -e "\n> Running Web Test Suite"
        testDockerComposeRun web "$(pwd)/vendor/phpunit/phpunit/phpunit" --testdox --do-not-cache-result --testsuite 
        Unit,Integration,Functional
        test_result=$?

        if [ $no_tear_down = "1" ]; then
            # This is used for when you want to debug the test containers
            exit $test_result
        fi


        testDockerCompose stop 2>&1 

        # Cleanup docker related leftovers
        docker rm -f $(docker ps -a | grep "${PROJECT}test" | awk $"(print $1)")
        docker network rm "${PROJECT}test"
        clearContainerCache

        exit $test_result
        ;;
    help)
        cat <<EOF
Usage:
  bash haz [command] [subcommand options]

Commands:
  help             View this message.
  setup            Build the containers.
  start            Start all the containers.
  stop             Stop all the containers.
  test             Run the test suite.
  reset            Reset the database without building the containers.
  reset-test       Reset the test database without building the containers.
  clean            Removes docker generated non-test container.
  composer         Manage an applications package dependencies.
  shell            Execute an interactive shell on an active container.

Arguments:
  -e | --env      Set a env option.
  -h | --help     Same as the help subcommand.
  -v | --verbose  Print executed commands to the CLI.
EOF
        ;;
    *)
        echo "Usage bash haz [-v|-h|-e K=V] subcommand [subcommand args]"
        exit 100
esac
exit
